= Links to Separate Sites

== Dropbox

http://css-tricks.com/snippets/html/post-data-to-an-iframe/[HOw to post data into a iFrame]

https://www.dropbox.com/developers/core/start/java[Core API for Java]

https://www.dropbox.com/developers/datastore/tutorial/js[Dropbox Data Store] tutorial

https://www.dropbox.com/home/Saves[Dropbox Home] - if signed on

https://www.dropbox.com/developers/datastore/sdks/js[Api]

https://github.com/dropbox/ClickTheBox-js[Click the box] and save state to Dropbox

.javascript
----
<script src="https://www.dropbox.com/static/api/dropbox-datastores-1.2-latest.js" type="text/javascript"></script>
----

== OAuth Receiver

.Example
----
<!doctype html>
<html>
<head>
	<script src="https://www.dropbox.com/static/api/dropbox-datastores-1.0-latest.js"></script>
</head>
<body>
	<script>
		Dropbox.AuthDriver.Popup.oauthReceiver();
	</script>
</body>
</html>
----

.index.html
----
<!doctype html>
<html>
<head>
	<title>Click the Box</title>
	<link rel="stylesheet" href="style.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="https://www.dropbox.com/static/api/dropbox-datastores-1.0-latest.js"></script>
</head>
<body>
	<h1>Click the Box</h1>
	<p id="instructions"  style="display:none">This game is easy. Just click the box.</p>
	<div id="container">
		<button id="login" style="display:none">Log in with Dropbox</button>
		<button id="box" style="display:none"></button>
	</div>
	<a id="reset" href="#">&pi;</a>
	<a id="logout" href="#" style="display:none">Log out</a>
	<script>
		if (window.location.href.indexOf('http://') === 0 && window.location.host.indexOf('127.0.0.1') !== 0) {
			window.location = window.location.href.replace('http://', 'https://');
		}

		// Be sure to use your own app key so you can set up your own redirect URI.
		var APP_KEY = '8i3v3z06x98zza5';

		function setLevel(level) {
			$('#box, #instructions').show();

			$('h1').text('CTB: Level ' + (level+1));

			// Start with 256x256 pixels, and reduce each dimension by half at each subsequent level.
			var size = Math.floor(256/Math.pow(2, level));
			$('#box').css({width: size, height: size});
			$('#container').css({padding: (256-size)/2});
		}

		var client = new Dropbox.Client({ key: APP_KEY });

		// Use a pop-up for auth.
		client.authDriver(new Dropbox.AuthDriver.Popup({ receiverUrl: window.location.href + 'oauth_receiver.html' }));

		// First check if we're already authenticated.
		client.authenticate({ interactive: false });

		if (client.isAuthenticated()) {
			// If we're authenticated, update the UI to reflect the logged in status.
			loggedIn();
		} else {
			// Otherwise show the login button.
			$('#login').show();
		}

		$('#login').click(function () {
			client.authenticate(function (err) {
				if (err) { alert('Error: ' + err); return; }
				loggedIn();
			});
		});

		function loggedIn() {
			$('#login').hide();
			var datastoreManager = new Dropbox.Datastore.DatastoreManager(client);

			datastoreManager.openDefaultDatastore(function (err, datastore) {
				if (err) { alert('Error: ' + err); return; }

				// Make sure we use the "max" resolution rule to resolve conflicts about which level we're on.
				var table = datastore.getTable('state');
				table.setResolutionRule('level', 'max');

				function getRecord() {
					// Use getOrInsert to provide a default of level 0.
					return table.getOrInsert('current_level', { level: 0 });
				}

				function updateLevel() {
					setLevel(getRecord().get('level'));
				}
				updateLevel();

				// Any time there's a change, update the current level.
				datastore.recordsChanged.addListener(updateLevel);

				$('#box').click(function (e) {
					e.preventDefault();

					// Increment the level.
					var record = getRecord();
					record.set('level', record.get('level') + 1);
				});

				$('#reset').click(function (e) {
					e.preventDefault();
					// Go back to level 0.
					getRecord().set('level', 0);
				});

				$('#logout').show().click(function (e) {
					e.preventDefault();
					client.signOut();
					$('#login').show();
					$('#box, #instructions').hide();
					$('#container').css('padding', 0);
					$('h1').text('Click the Box');
				});
			});
		}
	</script>
</body>
</html>
----



== Asciidoctor Links

http://rubygems.org/profiles/mojavelinux[RubyGems.org]

http://rubygems.org/gems/asciidoctor-pdf[Asciidoctor PDF Download]

http://asciidoctor.org/docs/migration/[Migrating to Asciidoctor 1.5.0]

https://github.com/asciidoctor/asciidoctor/issues[Asciidoctor Issue Tracker]

https://github.com/asciidoctor/asciidoctor-pdf/issues[Asciidoctor PDF  Issues]


== Using Extensions in Asciidoctor

http://mrhaki.blogspot.fr/2014/08/awesome-asciidoc-write-extensions-using.html[Awesome Asciidoc: Write Extensions Using Groovy (or Java)] - MrHaki explains how to write a Twitter ext.!

http://www.jroller.com/aalmiray/entry/gradle_glam_custom_asciidoctor_extensions[PigLatin Extension] by Andres Almiray

http://fr.slideshare.net/paulk_asert/groovy-databases[Grovy Database] access slides by Paul King

== U S Visa Links

http://travel.state.gov/content/visas/english.html[US State Dept. Visa]

Immigrant Visas

To reach the National Visa Center (immigrant visa inquiries, including assistance regarding the new DS-260, Immigrant Visa and Alien Registration Application) call: (603) 334-0700 (7:00 a.m. EST to 12:00 midnight EST) or e-mail: asknvc@state.gov. 

To reach the Kentucky Consular Center (Diversity Visa inquiries) call : (606) 526-7500 (7:30 a.m. EST to 4:00 .pm. EST).

http://travel.state.gov/content/visas/english/contact.html[Visa Contacts]

http://www.immihelp.com/greencard/replace-greencard.html[Replacement Green Cards] - the I90 form

http://france.usembassy.gov/visas.html[US Embassy Paris]

http://germany.usembassy.gov/visa/iv/contact/form/[US Diplomatic Service ] - Frankfurt

